name: 'Get Ref'
description: 'Will retrieve the acting ref name regardless of trigger'

inputs:
  custom_ref:
    description: 'Custom Ref Name Override'
    required: false

outputs:
  ref_name:
    description: 'Ref Name of triggering ref'
    value: ${{ steps.get_ref.outputs.ref_name }}

runs:
  using: 'composite'
  steps:
    - name: Get Ref
      id: get_ref
      run: |
        if [ -n "${{ inputs.custom_ref }}" ]; then
          echo "ref_name=${{ inputs.custom_ref }}" >> $GITHUB_OUTPUT

        elif [ "${{ github.event_name }}" = "pull_request" ]; then
          echo "ref_name=${{ github.head_ref }}" >> $GITHUB_OUTPUT

        elif [ "${{ github.event_name }}" = "push" ]; then
          echo "ref_name=${{ github.ref_name }}" >> $GITHUB_OUTPUT

        elif [ "${{ github.event_name }}" = "create" ]; then
          echo "ref_name=${{ github.ref_name }}" >> $GITHUB_OUTPUT

        elif [ "${{ github.event_name }}" = "delete" ]; then
          echo "ref_name=${{ github.event.ref }}" >> $GITHUB_OUTPUT

        else
          echo "ref_name=${{ github.ref_name }}" >> $GITHUB_OUTPUT

        fi
      shell: bash
