name: Playground

on:
  - push
  - pull_request
  - create

jobs:
  playground:
    runs-on: ubuntu-latest
    name: Playground ${{ github.event_name }}
    steps:
      - name: Print Event Name
        run: echo "${{ github.event_name }}"

      - name: Get Ref
        id: get_ref
        uses: ./

      - name: Print Ref
        run: echo "${{ steps.get_ref.outputs.ref_name }}"

      - name: Get Custom Ref
        id: get_custom_ref
        uses: ./
        with:
          custom_ref: feature/custom-ref

      - name: Print Ref
        run: echo "${{ steps.get_custom_ref.outputs.ref_name }}"
